theme = "catppuccin_mocha"

[editor]
mouse = false
rulers = [82]
line-number = "relative"
bufferline = "multiple"
true-color = true
color-modes = true
auto-completion = true
#[editor.insert]

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spacer", "position" ,"spinner", "read-only-indicator", "file-modification-indicator" , "register"]
center = ["version-control"]
separator = "|"
right = ["diagnostics" ,"file-encoding","file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
select = "underline" 

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
esc = ["collapse_selection" , "keep_primary_selection"]
"*" = ["move_char_right" , "move_prev_word_start" , "move_next_word_end" , "search_selection" , "search_next"]
"f" = [":format"] 
#C-f = [":new" , ":insert-output lf-pick" , ":theme default" , "select_all" , "split_selection_on_newline" , "goto_file" , "goto_last_modified_file" , ":buffer-close!" , ":theme catppuccin_mocha"]
#C-l = [":open  $(cat /tmp/hx_cmd)"]
C-R = [":run-shell-command go run ."]
C-B = [":run-shell-command go build ."]
C-q = [":config-reload"]
C-e = [":config-open"]
C-a = [":buffer-close"]
C-x = [":buffer-close!"]
C-O = [":buffer-close-others"]
C-L = [":o ~/.config/helix/languages.toml"]
C-g = [":new" , ":insert-output lazygit" , ":buffer-close!" , ":redraw"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[keys.normal."space"]
"*" = ["move_char_right" , "move_prev_word_start" , "move_next_word_end" , "search_selection" , "search_next"]
"f" = "file_picker_in_current_directory"
"<" = "file_picker_in_current_buffer_directory"

