[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
# indent = { tab-width = 4, unit = " " }

[[language]]
name = "cpp"
formatter = {command = "clang-format"}

 [language-server.emmet-ls]
 command = "emmet-ls"
 args = ["--studio"]

[[language]]
name = "html"
formatter = {command = "prettier"}
language-servers = ["vscode-html-language-server","emmet-ls"]
auto-format = true
# diagnostic-severity = ["Error", "Warning", "Info", "Hint"]

 [language-server.vscode-css-language-server.config]
 css = { validate = { enable = true } }
 scss = { validate = { enable = true } }
 less = { validate = { enable = true } }
 provideFormatter = true

[[language]]
 name = "css"
 formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
 language-servers = [ "vscode-css-language-server", "tailwindcss-react", "tailwindcss-ls"]
 auto-format = true

[[language]]
name = "javascript"
auto-format = true
formatter = {command = "prettier"}

[[language]]
name = "python"
auto-format = true
formatter = {command = "isort"}

[[language]]
name = "rust"
auto-format = true
formatter = {command = "rustfmt"}
